spring:
  application:
    name: joy-for-living-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
